version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - lampnet
    environment:
      - TZ=Asia/Dhaka

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init-exporter.sql:/docker-entrypoint-initdb.d/init-exporter.sql:ro
    networks:
      - lampnet

volumes:
  db_data:

networks:
  lampnet:
